name: Type Check

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - name: clone types
        run: |
          mkdir -p types
          cd types
          git clone https://github.com/imzlh/circu.js
          mv circu.js/types/* .
          wget https://github.com/denoland/deno/releases/download/v2.7.14/lib.deno.d.ts

      - run: pnpm run type-check
